# Site settings
title: Devout Design
email: contact@devoutdesign.com
description: >
  We provide custom website and mobile app development for Catholic churches and organizations.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.devoutdesign.com" # the base hostname & protocol for your site
twitter_username: devoutdesignllc
github_username:  devoutdesign

# Build settings
markdown: kramdown
sass:
    sass_dir: assets/_sass
